development:
  cloud_name: "dqhmtyqki"
  api_key: "939514836214629"
  api_secret: "QmUVbJ75q2LLT6sLSWhM-EPW2us"
  enhance_image_tag: true
  static_file_support: true

production:
  cloud_name: "dqhmtyqki"
  api_key: "939514836214629"
  api_secret: "QmUVbJ75q2LLT6sLSWhM-EPW2us"
  enhance_image_tag: true
  static_file_support: true
